---
- name: Check if ssh folder is provided
  delegate_to: localhost
  stat:
    path: "{{ ssh_folder_path }}"
  register: ssh_folder

- name: Populate ssh folder
  when: ssh_folder.stat.exists
  copy: 
    src: "{{ ssh_folder_path }}"
    dest: "~/.ssh"

- name: Generate ssh key
  become: true
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_ed25519
    force: no

- name: Add ssh key to ssh-agent
  shell:
    executable: bash 
    cmd: eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519