---
- name: Create .ssh folder
  file:
    path: ~/.ssh
    state: directory

- name: Populate ssh config
  copy:
    src: ./.dotfiles/ssh/config
    dest: ~/.ssh/config

- name: Generate ssh key
  become: true
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_ed25519
    force: no

- name: Add ssh key to ssh-agent
  shell:
    executable: bash 
    cmd: eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519

- name: Print ssh key
  debug:
    msg: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"