---
- name: Install required packages for macOS
  when: os == "MacOSX"
  become: true
  homebrew:
    name: "{{ packages_macos }}"
    state: latest

- name: Add fish apt repository
  when: os == "Ubuntu"
  become: true
  shell:
    executable: bash
    cmd: apt-add-repository ppa:fish-shell/release-3

- name: Install required packages for Ubuntu
  when: os == "Ubuntu"
  become: true
  apt:
    name: "{{ packages_ubuntu }}"
    state: latest

- name: Check if vimrc is provided
  delegate_to: localhost
  stat:
    path: "{{ vimrc_path }}"
  register: vimrc_file

- name: Populate .vimrc
  when: vimrc_file.stat.exists
  copy: 
    src: "{{ vimrc_path }}"
    dest: ~/.vimrc

- name: Check if gitconfig is provided
  delegate_to: localhost
  stat:
    path: "{{ git_config_path }}"
  register: git_config_file

- name: Populate .gitconfig
  when: git_config_file.stat.exists
  copy: 
    src: "{{ git_config_path }}"
    dest: ~/.gitconfig