---
- import_tasks: macos.yml
  when: os == "MacOSX"

- import_tasks: ubuntu.yml
  when: os == "Ubuntu"

- name: Check if vimrc is provided
  delegate_to: localhost
  stat:
    path: "{{ vimrc_path }}"
  register: vimrc_file

- name: Populate .vimrc
  when: vimrc_file.stat.exists
  copy: 
    src: "{{ vimrc_path }}"
    dest: ~/.vimrc

- name: Check if gitconfig is provided
  delegate_to: localhost
  stat:
    path: "{{ git_config_path }}"
  register: git_config_file

- name: Populate .gitconfig
  when: git_config_file.stat.exists
  copy: 
    src: "{{ git_config_path }}"
    dest: ~/.gitconfig