---
- name: Install oh-my-zsh
  shell: 
    executable: bash
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    creates: ~/.oh-my-zsh

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    force: yes

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    force: yes

- name: Install powerlevel10k
  git: 
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1
    force: yes

- name: Check if zshrc is provided
  delegate_to: localhost
  stat:
    path: "{{ zshrc_path }}"
  register: zshrc_file

- name: Populate .zshrc
  when: zshrc_file.stat.exists
  copy: 
    src: "{{ zshrc_path }}"
    dest: ~/.zshrc

- name: Check if p10k config is provided
  delegate_to: localhost
  stat:
    path: "{{ p10k_config_path }}"
  register: p10k_config_file

- name: Populate .p10k.zsh
  copy: 
    src: "{{ p10k_config_path }}"
    dest: ~/.p10k.zsh

- name: Enable 256-color terminal
  lineinfile:
    path: ~/.zshrc
    regexp: 'export TERM="xterm-256color"'
    line: 'export TERM="xterm-256color"'

- name: Set default shell to zsh
  become: true
  when: default_shell == "zsh"
  shell:
    executable: zsh
    cmd: chsh -s /bin/zsh {{ ansible_user }}