---
- name: Update the apt package index and install packages to allow apt to use a repository over HTTPS
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest

- name: Add docker gpg apt key
  become: true
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  become: true
  apt_repository: 
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker
  become: true
  apt: 
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes